- project:
    name: sandbox
    github-org: openstack-dev
    node: master
    vendor: myvendor

    jobs:
        - noop-check-communication
        - dsvm-tempest-full:
            node: 'devstack-precise || devstack-precise-check || d-p-c'
